    server {
        listen 880 default_server;
	listen [::]:880 default_server;
        server_name  localhost;
        location / {
        autoindex on;
        charset utf-8;
        root /mnt;
        }
    }
